import { AnalyticsEventBlueprint } from './analytics-growth-design.types';

export const analyticsEventBlueprintRegistry: AnalyticsEventBlueprint[] = [
  {
    name: 'public.page_view',
    category: 'public_funnel',
    origin: ['client', 'server'],
    allowedPayload: ['routeTemplate', 'contentCluster', 'sourceMedium', 'consentState'],
    forbiddenPayload: ['email', 'phone', 'message', 'subjectIdentifier', 'rawPayload'],
    serverAuthoritative: false,
    retentionPolicy: 'aggregate_after_90_days',
  },
  {
    name: 'seo_geo.guide_viewed',
    category: 'seo_geo',
    origin: ['client', 'server'],
    allowedPayload: ['slug', 'contentCluster', 'searchIntent', 'consentState'],
    forbiddenPayload: ['email', 'phone', 'ipAddress', 'subjectName'],
    serverAuthoritative: false,
    retentionPolicy: 'aggregate_after_90_days',
  },
  {
    name: 'checkout.started',
    category: 'checkout_billing',
    origin: ['server'],
    allowedPayload: ['orderId', 'serviceCode', 'priceSnapshotId', 'attributionSnapshotId'],
    forbiddenPayload: ['cardData', 'email', 'fiscalProfileRaw', 'providerPayload'],
    serverAuthoritative: true,
    retentionPolicy: 'business_audit_reference',
  },
  {
    name: 'payment.failed',
    category: 'checkout_billing',
    origin: ['webhook', 'server'],
    allowedPayload: ['paymentProvider', 'normalizedErrorCode', 'errorLedgerId', 'retryable'],
    forbiddenPayload: ['rawWebhook', 'cardData', 'email', 'secret'],
    serverAuthoritative: true,
    retentionPolicy: 'business_audit_reference',
  },
  {
    name: 'provider.request_failed',
    category: 'provider_openai',
    origin: ['server'],
    allowedPayload: ['providerCode', 'serviceCode', 'normalizedErrorCode', 'errorLedgerId'],
    forbiddenPayload: ['rawPayload', 'apiKey', 'subjectIdentifier', 'stackTrace'],
    serverAuthoritative: true,
    retentionPolicy: 'operational_error_reference',
  },
  {
    name: 'email.failed',
    category: 'email_notifications',
    origin: ['server', 'webhook'],
    allowedPayload: ['emailType', 'deliveryId', 'normalizedErrorCode', 'errorLedgerId'],
    forbiddenPayload: ['recipientEmail', 'emailBody', 'attachmentContent'],
    serverAuthoritative: true,
    retentionPolicy: 'delivery_audit_reference',
  },
];

export const analyticsForbiddenPayloadKeys = [
  'email',
  'phone',
  'fiscalCode',
  'vatNumber',
  'iban',
  'cardData',
  'rawPayload',
  'rawWebhook',
  'apiKey',
  'token',
  'secret',
  'prompt',
  'completion',
  'stackTrace',
  'ipAddress',
];
