import { Product } from './product.entity';

export type SeedProduct = Omit<Product, 'id' | 'createdAt' | 'updatedAt'>;

export const catalogSeedProducts: SeedProduct[] = [
  {
    code: 'COMPANY_ESSENTIAL',
    slug: 'verifica-azienda-essenziale',
    name: 'Verifica azienda essenziale',
    category: 'Affidabilità B2B',
    scenario: 'new-client',
    status: 'published',
    riskLevel: 'low',
    description: "Controlla stato, dati principali e primo indicatore operativo prima di iniziare un rapporto B2B.",
    publicPromise: "Dati aziendali principali e sintesi operativa per decidere il prossimo passo.",
    estimatedDelivery: 'pochi minuti',
    publicPriceCents: 1490,
    taxRate: 22,
    estimatedProviderCostCents: 25,
    checkoutFeeReserveCents: 55,
    supportReserveCents: 30,
    retryReserveCents: 15,
    targetGrossMarginRatio: 0.70,
    minimumGrossMarginRatio: 0.55,
    active: true,
    recommended: false,
    requiresLegalBasis: true,
    requiresComplianceReview: false,
    requiredInputs: ['Partita IVA o ragione sociale', 'Finalità professionale della verifica'],
    reportOutputs: ['Dati identificativi', 'Stato attività', 'Sintesi operativa', 'Limiti del report'],
    limits: ['Non garantisce pagamento o assenza di rischio', 'Non sostituisce istruttoria creditizia'],
    providerEndpoints: ['Company Start - Italia', 'Company Search - Italia', 'PEC Imprese - Italia', 'European VAT'],
    providerConfig: { provider: 'openapi', endpointGroup: 'company-essential' },
  },
  {
    code: 'COMPANY_PRO',
    slug: 'check-affidabilita-pro',
    name: 'Check Affidabilità Pro',
    category: 'Risk intelligence',
    scenario: 'new-client',
    status: 'published',
    riskLevel: 'medium',
    description: 'Report decisionale con scoring, segnali disponibili, soggetti collegati e prossima azione consigliata.',
    publicPromise: 'Raccogli segnali utili prima di vendere, spedire o concedere credito.',
    estimatedDelivery: 'pochi minuti',
    publicPriceCents: 2490,
    taxRate: 22,
    estimatedProviderCostCents: 220,
    checkoutFeeReserveCents: 75,
    supportReserveCents: 50,
    retryReserveCents: 25,
    targetGrossMarginRatio: 0.70,
    minimumGrossMarginRatio: 0.55,
    active: true,
    recommended: true,
    requiresLegalBasis: true,
    requiresComplianceReview: true,
    requiredInputs: ['Partita IVA o ragione sociale', 'Contesto della decisione', 'Finalità professionale lecita'],
    reportOutputs: ['Score sintetico', 'Segnali disponibili', 'Soggetti collegati', 'Prossima azione consigliata'],
    limits: ['Lo score è indicativo', 'Non garantisce solvibilità o pagamento'],
    providerEndpoints: ['Company Full - Italia', 'Credit Scoring Advanced - Italia', 'Negatività Impresa - Italia', 'Stakeholders Company - Italia'],
    providerConfig: { provider: 'openapi', endpointGroup: 'company-pro' },
  },
  {
    code: 'COMPANY_PRO_BALANCE',
    slug: 'affidabilita-pro-bilancio',
    name: 'Affidabilità Pro + Bilancio',
    category: 'Risk intelligence',
    scenario: 'new-client',
    status: 'published',
    riskLevel: 'medium',
    description: 'Approfondimento economico-finanziario per decisioni B2B più rilevanti, con bilancio se disponibile.',
    publicPromise: 'Aggiungi un approfondimento quando importo, continuità o esposizione rendono la decisione più importante.',
    estimatedDelivery: 'da pochi minuti, se disponibile',
    publicPriceCents: 3490,
    taxRate: 22,
    estimatedProviderCostCents: 700,
    checkoutFeeReserveCents: 95,
    supportReserveCents: 70,
    retryReserveCents: 35,
    targetGrossMarginRatio: 0.62,
    minimumGrossMarginRatio: 0.55,
    active: true,
    recommended: false,
    requiresLegalBasis: true,
    requiresComplianceReview: true,
    requiredInputs: ['Partita IVA o ragione sociale', 'Contesto economico della decisione', 'Finalità professionale lecita'],
    reportOutputs: ['Report Pro', 'Bilancio se disponibile', 'Sintesi economica', 'Limiti fonte'],
    limits: ['Bilancio disponibile solo se presente nella fonte', 'Non sostituisce consulenza finanziaria'],
    providerEndpoints: ['Company Full - Italia', 'Credit Scoring Advanced - Italia', 'Bilancio Imprese Italiane', 'Visura Protesti Società'],
    providerConfig: { provider: 'openapi', endpointGroup: 'company-pro-balance' },
  },
  {
    code: 'KYB_COMPLIANCE',
    slug: 'kyb-compliance',
    name: 'KYB Compliance',
    category: 'Compliance',
    scenario: 'partner-compliance',
    status: 'assisted',
    riskLevel: 'high',
    description: 'Verifica assetti, titolare effettivo, AML e segnali reputazionali disponibili per partner e fornitori strategici.',
    publicPromise: 'Sintesi KYB prudente per onboarding B2B sensibile e controlli su fornitori critici.',
    estimatedDelivery: 'da pochi minuti',
    publicPriceCents: 4990,
    taxRate: 22,
    estimatedProviderCostCents: 450,
    checkoutFeeReserveCents: 130,
    supportReserveCents: 180,
    retryReserveCents: 60,
    targetGrossMarginRatio: 0.70,
    minimumGrossMarginRatio: 0.60,
    active: true,
    recommended: false,
    requiresLegalBasis: true,
    requiresComplianceReview: true,
    requiredInputs: ['Partita IVA o identificativo azienda', 'Motivo della verifica', 'Ruolo del richiedente'],
    reportOutputs: ['Soggetti rilevanti', 'Titolare effettivo se disponibile', 'AML/PEP/sanctions dove applicabile', 'Sintesi compliance'],
    limits: ['Non certifica assenza totale di rischio', 'Può richiedere revisione manuale o documenti aggiuntivi'],
    providerEndpoints: ['Company Full - Italia', 'Titolare Effettivo', 'Antiriciclaggio (AML) - Italia', 'Stakeholders Company - Italia'],
    providerConfig: { provider: 'openapi', endpointGroup: 'kyb-compliance' },
  },
  {
    code: 'IBAN_CHECK',
    slug: 'verifica-iban',
    name: 'Verifica IBAN',
    category: 'Antifrode dati',
    scenario: 'payment-data',
    status: 'published',
    riskLevel: 'low',
    description: 'Controlla IBAN, banca, BIC e raggiungibilità SEPA prima di registrare o modificare coordinate di pagamento.',
    publicPromise: 'Riduci errori operativi prima di salvare dati di pagamento.',
    estimatedDelivery: 'tempo reale',
    publicPriceCents: 490,
    taxRate: 22,
    estimatedProviderCostCents: 20,
    checkoutFeeReserveCents: 35,
    supportReserveCents: 15,
    retryReserveCents: 5,
    targetGrossMarginRatio: 0.80,
    minimumGrossMarginRatio: 0.60,
    active: true,
    recommended: false,
    requiresLegalBasis: true,
    requiresComplianceReview: false,
    requiredInputs: ['IBAN', 'Finalità della verifica', 'Email operativa'],
    reportOutputs: ['Validità formato', 'Banca/BIC se disponibile', 'Area SEPA', 'Esito operativo'],
    limits: ['Non autorizza pagamenti', 'Non certifica la titolarità economica del conto se la fonte non lo consente'],
    providerEndpoints: ['IBAN Start'],
    providerConfig: { provider: 'openapi', endpointGroup: 'iban-check' },
  },
  {
    code: 'CONTACT_CHECK',
    slug: 'verifica-contatti',
    name: 'Verifica email e telefono',
    category: 'Antifrode dati',
    scenario: 'payment-data',
    status: 'published',
    riskLevel: 'low-medium',
    description: 'Valida email e numero mobile per ridurre lead falsi, bounce e onboarding con dati incompleti.',
    publicPromise: 'Migliora la qualità dei dati prima di attivare CRM, onboarding o comunicazioni operative.',
    estimatedDelivery: 'tempo reale',
    publicPriceCents: 490,
    taxRate: 22,
    estimatedProviderCostCents: 12,
    checkoutFeeReserveCents: 35,
    supportReserveCents: 15,
    retryReserveCents: 5,
    targetGrossMarginRatio: 0.80,
    minimumGrossMarginRatio: 0.60,
    active: true,
    recommended: false,
    requiresLegalBasis: true,
    requiresComplianceReview: false,
    requiredInputs: ['Email o numero mobile', 'Paese se disponibile', 'Finalità operativa'],
    reportOutputs: ['Formato', 'Raggiungibilità tecnica', 'Indicazioni anti-abuso', 'Esito sintetico'],
    limits: ['Non usare per spam o profilazione invasiva', 'La verifica tecnica non equivale a consenso marketing'],
    providerEndpoints: ['Verifica Email Advanced', 'Verifica Numero Cellulare Advanced'],
    providerConfig: { provider: 'openapi', endpointGroup: 'contact-check' },
  },
];
