export const settingsAdminDesignBlueprint = {
  version: '0.55.0',
  routes: [
    '/admin/settings',
    '/admin/settings/commerce',
    '/admin/settings/payments',
    '/admin/settings/provider-openapi',
    '/admin/settings/openai',
    '/admin/settings/errors',
    '/admin/settings/security',
  ],
  namespaces: [
    { key: 'commerce', label: 'Acquisti e checkout', primaryAction: 'Sospendi nuovi acquisti' },
    { key: 'payments', label: 'Pagamenti e rimborsi', primaryAction: 'Verifica provider pagamento' },
    { key: 'provider_openapi', label: 'Provider Openapi', primaryAction: 'Verifica configurazione provider' },
    { key: 'openai', label: 'OpenAI e AI assistita', primaryAction: 'Verifica budget e use case' },
    { key: 'errors', label: 'Errori operativi', primaryAction: 'Analizza criticita aperte' },
    { key: 'security', label: 'Sicurezza operativa', primaryAction: 'Controlla audit e bootstrap' },
  ],
  components: [
    'SettingsStatusHero',
    'SettingsNamespaceCard',
    'SettingControlRow',
    'SecretReferenceField',
    'PurchaseKillSwitchPanel',
    'ProviderHealthCard',
    'OpenAiBudgetGuardCard',
    'OperationalErrorTable',
    'OperationalErrorDetailPanel',
    'BuyerIpAuditBadge',
    'ReasonRequiredModal',
    'SettingsAuditTimeline',
  ],
  forbiddenUiPatterns: [
    'render secret values in clear text',
    'disable purchases only on the frontend',
    'close critical errors without reason',
    'show full raw buyer IP in tables',
    'publish AI output without human review',
  ],
} as const;
