import type { ProviderServiceMappingDesign } from '@clientiaffidabili/shared';

export const PROVIDER_MAPPING_VERSION = '2026-05-mvp-v1';

export const PROVIDER_SERVICE_MAPPINGS: ProviderServiceMappingDesign[] = [
  {
    productCode: 'COMPANY_ESSENTIAL',
    providerName: 'openapi',
    providerServiceCode: 'company-start-it+pec-sdi-enrichment',
    providerServiceVersion: PROVIDER_MAPPING_VERSION,
    deliveryMode: 'sync',
    enabledInSandbox: true,
    enabledInProduction: false,
    requiredInputs: ['vatNumberOrTaxCode'],
    optionalInputs: ['businessName', 'province'],
    estimatedCostCents: 180,
    maxAcceptedCostCents: 350,
    normalizationProfile: 'company-basic-profile',
    retryPolicy: 'safe_once',
    requiresManualReview: false,
    legalUseConfirmationRequired: true,
    customerVisibleOutput: ['anagrafica azienda', 'sede', 'PEC/SDI se disponibili', 'fonte e data'],
    hiddenProviderFields: ['rawProviderPayload', 'providerInternalIds', 'unneededPersonalFields'],
  },
  {
    productCode: 'COMPANY_PRO',
    providerName: 'openapi',
    providerServiceCode: 'company-full-it+credit-scoring',
    providerServiceVersion: PROVIDER_MAPPING_VERSION,
    deliveryMode: 'async_polling',
    enabledInSandbox: true,
    enabledInProduction: false,
    requiredInputs: ['vatNumberOrTaxCode'],
    optionalInputs: ['businessName', 'includeNegativeEvents'],
    estimatedCostCents: 890,
    maxAcceptedCostCents: 1400,
    normalizationProfile: 'company-risk-profile',
    retryPolicy: 'manual_only',
    requiresManualReview: false,
    legalUseConfirmationRequired: true,
    customerVisibleOutput: ['sintesi rischio', 'segnali da approfondire', 'evidenze fonte', 'limiti verifica'],
    hiddenProviderFields: ['rawScoreFormula', 'providerRequestId', 'rawProviderPayload'],
  },
  {
    productCode: 'COMPANY_PRO_BALANCE',
    providerName: 'openapi',
    providerServiceCode: 'company-full-it+bilancio-imprese-italiane',
    providerServiceVersion: PROVIDER_MAPPING_VERSION,
    deliveryMode: 'async_polling',
    enabledInSandbox: true,
    enabledInProduction: false,
    requiredInputs: ['vatNumberOrTaxCode'],
    optionalInputs: ['fiscalYear', 'businessName'],
    estimatedCostCents: 3850,
    maxAcceptedCostCents: 4500,
    normalizationProfile: 'company-risk-financial-profile',
    retryPolicy: 'manual_only',
    requiresManualReview: true,
    legalUseConfirmationRequired: true,
    customerVisibleOutput: ['profilo azienda', 'bilancio disponibile', 'indicatori descrittivi', 'limiti temporali'],
    hiddenProviderFields: ['rawFinancialDocument', 'providerInternalIds'],
  },
  {
    productCode: 'KYB_COMPLIANCE',
    providerName: 'openapi',
    providerServiceCode: 'aml+titolare-effettivo+sanctions-pep',
    providerServiceVersion: PROVIDER_MAPPING_VERSION,
    deliveryMode: 'async_polling',
    enabledInSandbox: true,
    enabledInProduction: false,
    requiredInputs: ['vatNumberOrTaxCode', 'declaredBusinessPurpose'],
    optionalInputs: ['beneficialOwnerName', 'beneficialOwnerTaxCode'],
    estimatedCostCents: 2100,
    maxAcceptedCostCents: 3200,
    normalizationProfile: 'kyb-compliance-profile',
    retryPolicy: 'manual_only',
    requiresManualReview: true,
    legalUseConfirmationRequired: true,
    customerVisibleOutput: ['stato verifica KYB', 'alert da approfondire', 'fonti consultate', 'limiti verifica'],
    hiddenProviderFields: ['rawAmlPayload', 'sensitivePersonalData', 'providerInternalIds'],
  },
  {
    productCode: 'IBAN_VERIFY',
    providerName: 'openapi',
    providerServiceCode: 'iban-start',
    providerServiceVersion: PROVIDER_MAPPING_VERSION,
    deliveryMode: 'sync',
    enabledInSandbox: true,
    enabledInProduction: false,
    requiredInputs: ['iban'],
    optionalInputs: ['holderName'],
    estimatedCostCents: 60,
    maxAcceptedCostCents: 120,
    normalizationProfile: 'payment-data-profile',
    retryPolicy: 'safe_once',
    requiresManualReview: false,
    legalUseConfirmationRequired: true,
    customerVisibleOutput: ['validità IBAN', 'esito verifica disponibile', 'limiti verifica'],
    hiddenProviderFields: ['fullIbanInLogs', 'rawProviderPayload'],
  },
  {
    productCode: 'CONTACT_VERIFY',
    providerName: 'openapi',
    providerServiceCode: 'email-start+mobile-start',
    providerServiceVersion: PROVIDER_MAPPING_VERSION,
    deliveryMode: 'sync',
    enabledInSandbox: true,
    enabledInProduction: false,
    requiredInputs: ['emailOrPhone'],
    optionalInputs: ['countryCode'],
    estimatedCostCents: 80,
    maxAcceptedCostCents: 160,
    normalizationProfile: 'contact-data-profile',
    retryPolicy: 'safe_once',
    requiresManualReview: false,
    legalUseConfirmationRequired: true,
    customerVisibleOutput: ['validità contatto', 'raggiungibilità tecnica se disponibile', 'limiti verifica'],
    hiddenProviderFields: ['rawProviderPayload', 'carrierTechnicalMetadata'],
  },
];

export function getProviderMapping(productCode: string): ProviderServiceMappingDesign | undefined {
  return PROVIDER_SERVICE_MAPPINGS.find((mapping) => mapping.productCode === productCode);
}

export function assertProviderMapping(productCode: string): ProviderServiceMappingDesign {
  const mapping = getProviderMapping(productCode);
  if (!mapping) throw new Error(`Missing provider mapping for product ${productCode}`);
  return mapping;
}
