import type { ProviderServiceMappingAnalysis } from '@clientiaffidabili/shared';

export const OPENAPI_PROVIDER_ANALYSIS = {
  provider: 'openapi',
  executionRule: 'Provider calls are server-side only and can start only after a paid order is confirmed by webhook.',
  credentialRule: 'OPENAPI credentials must stay in API runtime secrets and must never be exposed to Next.js public env or browser code.',
  idempotencyRule: 'Every provider request must use orderId + checkId + productCode as the stable idempotency base.',
  costRule: 'The estimated provider cost used in pricing is frozen again as providerCostSnapshot before the provider request is created.',
  verificationGap: 'Official partner/developer documentation and real account credentials must be verified before M5-S production calls are enabled.',
} as const;

export const MVP_PROVIDER_SERVICE_MAPPING_ANALYSIS: ProviderServiceMappingAnalysis[] = [
  {
    productCode: 'COMPANY_ESSENTIAL',
    providerName: 'openapi',
    providerServiceCode: 'company-start-it + pec/sdi optional enrichment',
    deliveryMode: 'sync',
    requiredInputs: ['vatNumber or taxCode', 'businessName fallback'],
    optionalInputs: ['province', 'legalForm'],
    expectedCostCents: 180,
    costVolatility: 'medium',
    normalizationProfile: 'company-basic-profile',
    complianceNotes: ['B2B only', 'show source timestamp', 'do not state solvency guarantee'],
  },
  {
    productCode: 'COMPANY_PRO',
    providerName: 'openapi',
    providerServiceCode: 'company-full-it + credit-scoring-start/top based on availability',
    deliveryMode: 'async_polling',
    requiredInputs: ['vatNumber or taxCode', 'businessName fallback'],
    optionalInputs: ['includeFinancials', 'includeNegativeEvents'],
    expectedCostCents: 890,
    costVolatility: 'high',
    normalizationProfile: 'company-risk-profile',
    complianceNotes: ['evidence-based scoring only', 'manual review if provider response is partial', 'no automatic rejection advice'],
  },
  {
    productCode: 'COMPANY_PRO_BALANCE',
    providerName: 'openapi',
    providerServiceCode: 'company-full-it + bilancio-imprese-italiane',
    deliveryMode: 'async_polling',
    requiredInputs: ['vatNumber or taxCode'],
    optionalInputs: ['fiscalYear'],
    expectedCostCents: 3850,
    costVolatility: 'high',
    normalizationProfile: 'company-risk-financial-profile',
    complianceNotes: ['financial statement availability may vary', 'must communicate delivery time before payment'],
  },
  {
    productCode: 'KYB_COMPLIANCE',
    providerName: 'openapi',
    providerServiceCode: 'aml-it + titolare-effettivo + sanctions/pep where available',
    deliveryMode: 'async_polling',
    requiredInputs: ['vatNumber or taxCode', 'declaredBusinessPurpose'],
    optionalInputs: ['beneficialOwnerName', 'beneficialOwnerTaxCode'],
    expectedCostCents: 2100,
    costVolatility: 'high',
    normalizationProfile: 'kyb-compliance-profile',
    complianceNotes: ['strong lawful-use confirmation', 'manual review for high-risk results', 'no consumer investigative wording'],
  },
  {
    productCode: 'IBAN_VERIFY',
    providerName: 'openapi',
    providerServiceCode: 'iban-start',
    deliveryMode: 'sync',
    requiredInputs: ['iban'],
    optionalInputs: ['holderName'],
    expectedCostCents: 60,
    costVolatility: 'low',
    normalizationProfile: 'payment-data-profile',
    complianceNotes: ['validate format before provider call', 'do not store full IBAN longer than required without policy'],
  },
  {
    productCode: 'CONTACT_VERIFY',
    providerName: 'openapi',
    providerServiceCode: 'email-start + mobile-start or advanced',
    deliveryMode: 'sync',
    requiredInputs: ['email or phone'],
    optionalInputs: ['countryCode'],
    expectedCostCents: 80,
    costVolatility: 'low',
    normalizationProfile: 'contact-verification-profile',
    complianceNotes: ['no marketing use implied', 'purpose limitation visible in checkout'],
  },
];

