export const partnerPortalDesign = {
  sprint: 'M12-P',
  version: '0.39.0',
  positioning: 'Portale API controllato per partner e reseller, sandbox-first e live su approvazione.',
  navigation: [
    'Panoramica',
    'API key',
    'Sandbox',
    'Documentazione',
    'Usage',
    'Billing',
    'Webhook',
    'Go live',
    'Supporto',
  ],
  onboardingStates: [
    'draft_profile',
    'sandbox_enabled',
    'sandbox_testing',
    'live_review_requested',
    'live_changes_required',
    'live_approved',
    'live_suspended',
  ],
  guardrails: [
    'API key hashate e mostrate una sola volta',
    'Sandbox separata da live',
    'Produzione solo dopo review',
    'Rate limit e scope obbligatori',
    'Idempotency-Key obbligatoria per richieste costose',
    'Credit wallet prima del consumo provider',
    'Usage ledger append-only',
    'Webhook partner firmati',
    'Nessun raw payload provider esposto',
  ],
  primaryCtas: {
    draft_profile: 'Completa profilo partner',
    sandbox_enabled: 'Genera API key sandbox',
    sandbox_testing: 'Esegui test sandbox',
    live_review_requested: 'Controlla stato revisione',
    live_changes_required: 'Correggi configurazione',
    live_approved: 'Crea API key live',
    live_suspended: 'Contatta supporto operations',
  },
} as const;
