import { SandboxScenarioBlueprint } from './sandbox-certification-design.types';
import type { SandboxScenarioRuntime } from './sandbox-certification-runtime.types';

export const sandboxCertificationScenarioRegistry: SandboxScenarioBlueprint[] = [
  {
    id: 'stripe-payment-success',
    area: 'payments.stripe',
    title: 'Stripe sandbox payment success creates coherent order and ledger',
    blockerForRc: true,
    requiredEvidence: ['payment_ledger', 'webhook_event', 'order_snapshot'],
    passCriteria: ['order_paid', 'single_provider_trigger', 'idempotent_webhook'],
    failCriteria: ['double_payment_ledger', 'provider_called_before_payment'],
  },
  {
    id: 'stripe-payment-failure',
    area: 'payments.stripe',
    title: 'Stripe failed payment does not create provider calls or paid entitlement',
    blockerForRc: true,
    requiredEvidence: ['payment_ledger', 'webhook_event', 'order_snapshot'],
    passCriteria: ['order_not_paid', 'provider_not_called', 'customer_can_retry'],
    failCriteria: ['paid_state_without_payment', 'provider_called_unpaid'],
  },
  {
    id: 'stripe-refund-full',
    area: 'payments.stripe',
    title: 'Stripe full refund updates refund ledger and customer notification',
    blockerForRc: true,
    requiredEvidence: ['refund_ledger', 'email_delivery', 'audit_event'],
    passCriteria: ['refund_recorded_once', 'order_state_consistent'],
    failCriteria: ['double_refund', 'missing_audit'],
  },
  {
    id: 'paypal-payment-success',
    area: 'payments.paypal',
    title: 'PayPal sandbox payment success is reconciled without enabling unverified live flow',
    blockerForRc: false,
    requiredEvidence: ['payment_ledger', 'webhook_event', 'settings_snapshot'],
    passCriteria: ['paypal_reconciled', 'feature_flag_checked', 'ledger_append_only'],
    failCriteria: ['paypal_live_enabled_without_certification', 'missing_reconciliation'],
    featureFlagIfWaived: 'payments.paypal.enabled',
  },
  {
    id: 'openapi-provider-post-payment',
    area: 'provider.openapi',
    title: 'Openapi provider call can run only after confirmed payment or reserved credit',
    blockerForRc: true,
    requiredEvidence: ['provider_request', 'cost_snapshot', 'order_payment_state'],
    passCriteria: ['blocked_before_payment', 'idempotency_key_present'],
    failCriteria: ['provider_called_unpaid', 'missing_cost_snapshot'],
  },
  {
    id: 'openapi-provider-failure-ledger',
    area: 'provider.openapi',
    title: 'Openapi provider failure creates retry-safe operational error ledger',
    blockerForRc: true,
    requiredEvidence: ['provider_request', 'audit_event', 'error_ledger'],
    passCriteria: ['safe_error_recorded', 'retry_policy_visible', 'raw_payload_redacted'],
    failCriteria: ['raw_provider_payload_exposed', 'missing_retry_decision'],
  },
  {
    id: 'email-pdf-secure-link',
    area: 'email.delivery',
    title: 'Document ready email uses secure link and delivery ledger',
    blockerForRc: true,
    requiredEvidence: ['email_delivery', 'secure_link', 'report_snapshot'],
    passCriteria: ['secure_link_expiring', 'delivery_status_tracked'],
    failCriteria: ['raw_pdf_public_url', 'missing_delivery_ledger'],
  },
  {
    id: 'report-pdf-access-control',
    area: 'report.pdf',
    title: 'Report PDF access is authenticated or tokenized and audit logged',
    blockerForRc: true,
    requiredEvidence: ['secure_link', 'report_snapshot', 'audit_event'],
    passCriteria: ['token_hash_only', 'download_audited', 'account_scope_checked'],
    failCriteria: ['public_pdf_url', 'missing_download_audit'],
  },
  {
    id: 'openai-disabled-by-default',
    area: 'ai.openai',
    title: 'OpenAI copilot is disabled by default and never auto-publishes',
    blockerForRc: false,
    requiredEvidence: ['settings_snapshot', 'copilot_draft'],
    passCriteria: ['disabled_default', 'draft_only'],
    failCriteria: ['auto_publish', 'raw_sensitive_context_sent'],
    featureFlagIfWaived: 'openai.copilot.enabled',
  },
  {
    id: 'auth-password-reset-email',
    area: 'auth.accounts',
    title: 'Password reset sends secure email event without leaking token',
    blockerForRc: true,
    requiredEvidence: ['auth_event', 'email_delivery', 'secure_link'],
    passCriteria: ['token_hash_only', 'email_delivery_tracked', 'expiry_present'],
    failCriteria: ['token_in_logs', 'missing_email_event'],
  },
  {
    id: 'customer-dashboard-fallback',
    area: 'customer.dashboard',
    title: 'Customer dashboard explains paid order, pending provider and support fallback',
    blockerForRc: true,
    requiredEvidence: ['dashboard_state', 'customer_task', 'support_ticket'],
    passCriteria: ['next_action_visible', 'no_raw_provider_payload', 'support_route_available'],
    failCriteria: ['customer_blocked_without_message', 'sensitive_payload_visible'],
  },
  {
    id: 'partner-api-sandbox-idempotency',
    area: 'partner.api',
    title: 'Partner API sandbox requires idempotency and never consumes live credit unexpectedly',
    blockerForRc: true,
    requiredEvidence: ['partner_api_log', 'credit_ledger', 'audit_event'],
    passCriteria: ['idempotency_required', 'sandbox_scope_checked', 'no_live_credit_consumed'],
    failCriteria: ['missing_idempotency', 'live_credit_consumed_in_sandbox'],
  },
  {
    id: 'seo-cms-publication-guardrail',
    area: 'seo.cms',
    title: 'CMS guide publication keeps claim guardrails and schema coherent with visible content',
    blockerForRc: false,
    requiredEvidence: ['cms_publication', 'security_scan', 'audit_event'],
    passCriteria: ['no_forbidden_claims', 'schema_matches_visible_content'],
    failCriteria: ['guaranteed_solvency_claim', 'schema_claim_not_visible'],
  },
  {
    id: 'docker-coolify-smoke',
    area: 'docker.coolify',
    title: 'Docker and Coolify smoke commands are prepared and block RC until executed',
    blockerForRc: true,
    requiredEvidence: ['docker_smoke', 'settings_snapshot'],
    passCriteria: ['healthcheck_paths_known', 'env_required_documented'],
    failCriteria: ['production_ready_claim_without_smoke', 'missing_healthcheck'],
  },
  {
    id: 'security-secret-scan',
    area: 'security.audit',
    title: 'Secret scan blocks live keys and frontend secret exposure',
    blockerForRc: true,
    requiredEvidence: ['security_scan', 'audit_event'],
    passCriteria: ['no_live_key_hardcoded', 'no_public_secret'],
    failCriteria: ['live_key_in_repo', 'next_public_secret_detected'],
  },
];

const runtimeDefaults: Record<string, Pick<SandboxScenarioRuntime, 'providerMode' | 'automationLevel' | 'estimatedDurationSeconds' | 'refundRelevant' | 'retryEligible' | 'rollbackAction' | 'ownerRole'>> = {
  'stripe-payment-success': {
    providerMode: 'mock',
    automationLevel: 'sandbox_adapter',
    estimatedDurationSeconds: 45,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Disabilitare payments.stripe.enabled e mantenere ordini in pending review.',
    ownerRole: 'billing_admin',
  },
  'stripe-payment-failure': {
    providerMode: 'mock',
    automationLevel: 'sandbox_adapter',
    estimatedDurationSeconds: 35,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Bloccare retry automatici e mostrare azione di pagamento manuale.',
    ownerRole: 'billing_admin',
  },
  'stripe-refund-full': {
    providerMode: 'mock',
    automationLevel: 'sandbox_adapter',
    estimatedDurationSeconds: 50,
    refundRelevant: true,
    retryEligible: false,
    rollbackAction: 'Sospendere rimborsi automatici e passare a review billing.',
    ownerRole: 'billing_admin',
  },
  'paypal-payment-success': {
    providerMode: 'mock',
    automationLevel: 'sandbox_adapter',
    estimatedDurationSeconds: 50,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Tenere payments.paypal.enabled disattivato fino a certificazione completa.',
    ownerRole: 'billing_admin',
  },
  'openapi-provider-post-payment': {
    providerMode: 'mock',
    automationLevel: 'sandbox_adapter',
    estimatedDurationSeconds: 60,
    refundRelevant: true,
    retryEligible: true,
    rollbackAction: 'Disabilitare provider_openapi.openapi.callsEnabled e mantenere report in attesa.',
    ownerRole: 'operations_admin',
  },
  'openapi-provider-failure-ledger': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 30,
    refundRelevant: true,
    retryEligible: true,
    rollbackAction: 'Aprire error ledger, valutare retry sicuro o rimborso secondo policy.',
    ownerRole: 'operations_admin',
  },
  'email-pdf-secure-link': {
    providerMode: 'mock',
    automationLevel: 'sandbox_adapter',
    estimatedDurationSeconds: 30,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Disabilitare allegati e usare dashboard fallback con secure link rigenerabile.',
    ownerRole: 'support_admin',
  },
  'report-pdf-access-control': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 25,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Revocare link, rigenerare token e mostrare download solo in area cliente.',
    ownerRole: 'operations_admin',
  },
  'openai-disabled-by-default': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 15,
    refundRelevant: false,
    retryEligible: false,
    rollbackAction: 'Lasciare openai.enabled spento e consentire solo bozze interne approvate.',
    ownerRole: 'platform_admin',
  },
  'auth-password-reset-email': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 20,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Sospendere reset non verificati e forzare rigenerazione token hash-only.',
    ownerRole: 'security_admin',
  },
  'customer-dashboard-fallback': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 20,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Mostrare stato protetto e aprire ticket di supporto operativo.',
    ownerRole: 'support_admin',
  },
  'partner-api-sandbox-idempotency': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 30,
    refundRelevant: true,
    retryEligible: true,
    rollbackAction: 'Revocare key sandbox sospetta e bloccare consumo crediti live.',
    ownerRole: 'partner_admin',
  },
  'seo-cms-publication-guardrail': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 15,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Rimettere pagina in draft e correggere claim/schema prima di pubblicare.',
    ownerRole: 'content_admin',
  },
  'docker-coolify-smoke': {
    providerMode: 'manual',
    automationLevel: 'manual_evidence',
    estimatedDurationSeconds: 180,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Bloccare RC finche smoke reale Docker/Coolify non viene allegato.',
    ownerRole: 'devops_admin',
  },
  'security-secret-scan': {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 10,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Rimuovere segreti, ruotare credenziali e rieseguire secret scan.',
    ownerRole: 'security_admin',
  },
};

export const sandboxCertificationRuntimeRegistry: SandboxScenarioRuntime[] = sandboxCertificationScenarioRegistry.map((scenario) => ({
  ...scenario,
  ...(runtimeDefaults[scenario.id] ?? {
    providerMode: 'mock',
    automationLevel: 'mock_first',
    estimatedDurationSeconds: 30,
    refundRelevant: false,
    retryEligible: true,
    rollbackAction: 'Bloccare RC e aprire remediation operativa.',
    ownerRole: 'operations_admin',
  }),
}));
