import type { ObjectAuthorizationPolicy, ProductionGateCheck, SecurityControlBlueprint } from './security-hardening.types';

export const securityControls: SecurityControlBlueprint[] = [
  {
    code: 'SEC-AUTH-001',
    title: 'Auth, RBAC and object-level authorization on customer/admin APIs',
    severity: 'p0',
    status: 'implemented',
    owner: 'api',
    implementationTarget: 'guards/auth.guard.ts + guards/object-ownership.guard.ts',
    qaEvidence: ['IDOR/BOLA regression tests', 'role matrix tests'],
    blocksProduction: true,
  },
  {
    code: 'SEC-WEBHOOK-001',
    title: 'Signed and idempotent Stripe/PayPal webhook processing',
    severity: 'p0',
    status: 'implemented',
    owner: 'api',
    implementationTarget: 'webhooks/webhook-verification.service.ts',
    qaEvidence: ['invalid signature test', 'duplicate webhook test', 'replay test'],
    blocksProduction: true,
  },
  {
    code: 'SEC-SECRETS-001',
    title: 'Secret scan and Coolify backend-only secret policy',
    severity: 'p0',
    status: 'implemented',
    owner: 'devops',
    implementationTarget: 'scripts/security-secret-scan.js',
    qaEvidence: ['secret scan passed', 'no NEXT_PUBLIC secret leakage'],
    blocksProduction: true,
  },
  {
    code: 'SEC-BACKUP-001',
    title: 'Backup and restore drill before production',
    severity: 'p0',
    status: 'implemented',
    owner: 'devops',
    implementationTarget: 'docs/security/24_INCIDENT_BACKUP_RESTORE_RUNBOOK.md',
    qaEvidence: ['restore drill report'],
    blocksProduction: true,
  },
  {
    code: 'SEC-LOG-001',
    title: 'PII, secrets and raw provider payload redaction',
    severity: 'p0',
    status: 'implemented',
    owner: 'api',
    implementationTarget: 'redaction/redaction.service.ts',
    qaEvidence: ['log redaction test'],
    blocksProduction: true,
  },

  {
    code: 'SEC-GATE-001',
    title: 'Production gate endpoint and static QA gate for go-live readiness',
    severity: 'p0',
    status: 'implemented',
    owner: 'security',
    implementationTarget: 'security.module.ts + scripts/security-production-gate.js',
    qaEvidence: ['production gate script passed', 'runtime gate endpoint returns blockers'],
    blocksProduction: true,
  },
];

export const objectAuthorizationPolicies: ObjectAuthorizationPolicy[] = [
  {
    resourceType: 'order',
    requiresAuth: true,
    customerRoles: ['customer_owner', 'customer_admin', 'customer_analyst'],
    adminRoles: ['operations', 'billing', 'support', 'super_admin'],
    ownershipField: 'accountId',
    auditOnRead: false,
    auditOnWrite: true,
    rawPayloadAllowed: false,
  },
  {
    resourceType: 'report',
    requiresAuth: true,
    customerRoles: ['customer_owner', 'customer_admin', 'customer_analyst', 'customer_viewer'],
    adminRoles: ['analyst', 'compliance', 'operations', 'super_admin'],
    ownershipField: 'accountId',
    auditOnRead: true,
    auditOnWrite: true,
    rawPayloadAllowed: false,
  },
  {
    resourceType: 'refund',
    requiresAuth: true,
    customerRoles: ['customer_owner', 'customer_billing'],
    adminRoles: ['billing', 'super_admin'],
    ownershipField: 'accountId',
    auditOnRead: true,
    auditOnWrite: true,
    rawPayloadAllowed: false,
  },
  {
    resourceType: 'provider_request',
    requiresAuth: true,
    customerRoles: [],
    adminRoles: ['operations', 'compliance', 'super_admin'],
    ownershipField: 'parentResource',
    auditOnRead: true,
    auditOnWrite: true,
    rawPayloadAllowed: false,
  },
];

export const productionGateChecks: ProductionGateCheck[] = [

  {
    code: 'GATE-SECRETS',
    title: 'Secret scan completed and no frontend secret leakage found',
    severity: 'p0',
    commandOrEvidence: 'node scripts/security-secret-scan.js',
    passCriteria: 'no real secrets, keys or tokens committed to repository files',
    blocksProduction: true,
  },
  {
    code: 'GATE-BUILD',
    title: 'Real install/typecheck/build completed',
    severity: 'p0',
    commandOrEvidence: 'pnpm install && pnpm -r typecheck && pnpm -r build',
    passCriteria: 'all commands exit 0 in a clean environment',
    blocksProduction: true,
  },
  {
    code: 'GATE-BOLA',
    title: 'Object-level authorization regression suite passed',
    severity: 'p0',
    commandOrEvidence: 'security QA report with cross-account denial tests',
    passCriteria: 'all manipulated IDs return safe 403/404 responses',
    blocksProduction: true,
  },
  {
    code: 'GATE-WEBHOOKS',
    title: 'Webhook signature/idempotency/replay tests passed',
    severity: 'p0',
    commandOrEvidence: 'webhook security test report',
    passCriteria: 'invalid signatures rejected and duplicate events have no duplicate effects',
    blocksProduction: true,
  },
  {
    code: 'GATE-RESTORE',
    title: 'Backup restore drill completed',
    severity: 'p0',
    commandOrEvidence: 'docs/qa/RESTORE_DRILL_REPORT.md',
    passCriteria: 'orders, reports, payments, audit and users verified after restore',
    blocksProduction: true,
  },
];
